name: Scrape Restaurant Menus

on:
  schedule:
    # Run at 8am, 10am, and 11am Prague time (CET/CEST)
    # GitHub Actions uses UTC, so we need to adjust:
    # 8am CET = 7am UTC (winter) or 6am UTC (summer)
    # 10am CET = 9am UTC (winter) or 8am UTC (summer)
    # 11am CET = 10am UTC (winter) or 9am UTC (summer)
    # Using both times to handle DST changes
    - cron: '0 6,7 * * 1-5'   # 8am Prague time
    - cron: '0 8,9 * * 1-5'   # 10am Prague time  
    - cron: '0 9,10 * * 1-5'  # 11am Prague time
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - master
    paths:
      - 'lib/scrapers/**'
      - '.github/workflows/scrape-menus.yml'

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install chromium

    - name: Run scrapers
      run: npm run scrape
      env:
        NODE_ENV: production

    - name: Check if menu data changed
      id: check_changes
      run: |
        if [[ -n $(git status --porcelain public/data/menus/) ]]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push if changed
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add public/data/menus/
        git commit -m "🍽️ Update restaurant menus [skip ci]

        Automated menu update from GitHub Actions
        Time: $(date +'%Y-%m-%d %H:%M:%S')"
        git push